### ISSUE TITLE
Create a better configuration system based on yaml files

### ISSUE THREAD

**Issue by vimukthi-git** [beanstalkg/beanstalkg#39]
We can try do golang libraries to do this once we agree on which one to use.

**Comment by stephenwithav** [comment]
Which configuration directives should be moved to yaml?  The command line switches?

**Comment by stephenwithav** [comment]
@vimukthi-git I'd like to work on this tomorrow.  `go-yaml` is my go to.

**Comment by vimukthi-git** [comment]
@stephenwithav there is not much to move right now, they are basically the parameters taken as command line arguments in main. You can ignore `proxy_mode` since I want to remove it. 
One of the things I care about is to have the parameters defined in `yaml` to be read from the environment for example the `port`.  this is useful for container environments.

**Comment by stephenwithav** [comment]
@vimukthi-git understood.  I'll find a yaml package that allows environment variables to override.

Or I'll just overwrite anything that's also specified in the environment.

**Comment by vimukthi-git** [comment]
@stephenwithav great let me know when you have found a good one. 

You can take your time with this as its prioritised for v0.8.0 in our roadmap.

**Comment by stephenwithav** [comment]
https://github.com/spf13/viper

@vimukthi-git this library will work well.

**Comment by vimukthi-git** [comment]
looks good, I have seen this lib before. We can go with it no problem.

**Comment by stephenwithav** [comment]
@vimukthi-git I'm about to push.  The compiler complained when I removed `proxy_mode` from the config (variable defined and not used), so I went ahead and removed proxy support altogether since you wanted it gone.

Removing proxy support removed the call to `getConfig`, which led to the not used error for `env`, so I removed it, too.

**Comment by vimukthi-git** [comment]
@stephenwithav can we try https://github.com/jinzhu/configor ? seems more simple and matching to our requirement.

**Comment by stephenwithav** [comment]
@vimukthi-git we certainly can try.  The update will be pushed tomorrow.

**Comment by stephenwithav** [comment]
@vimukthi-git given flags, environment, and YAML, which is the highest priority?

I'm assuming command-line flags override environment variables, which override the YAML configuration.

Do you agree?

**Comment by stephenwithav** [comment]
@vimukthi-git `configor` works, but doesn't follow the 12 Factor guidelines.  Environment variables override command-line flags, when it should be the opposite.

**Comment by stephenwithav** [comment]
See here for the test: https://github.com/stephenwithav/configor-test

**Comment by vimukthi-git** [comment]
@stephenwithav thanks for the update. Can we use it for now and may be fork and change it later to make it follow the correct override order?

**Comment by stephenwithav** [comment]
@vimukthi-git yes we can.  And I can mimic the 12 Factor behavior with `configor`, if needed.

**Comment by stephenwithav** [comment]
The example repo is now corrected to ensure that command-line flags override environment variables.  I'll integrate it shortly.
