### ISSUE TITLE
Cannot resolve getConfig

### ISSUE THREAD

**Issue by heinrich10** [beanstalkg/beanstalkg#85]
the getConfig cannot be resolved by importing github.com/beanstalkg/beanstalkg/config.
I have already moved config.go, config.json, and config.yml to config directory.

here is a sample error:
![image](https://user-images.githubusercontent.com/3993331/27094283-30a8fb78-509c-11e7-8887-6707dc3cc751.png)

please help to resolve this.

**Comment by stephenwithav** [comment]
@heinrich10 which branch are you in?

**Comment by stephenwithav** [comment]
Answered in #66.
